using System;

public enum UIDisplayEvnt
{
	BULLET_ACROSS,
	CONTINOUS_KILL,
	HEADSHOT,
	FLASH_RELOAD,
	DOUBLE_DNA,
	DOUBLE_COIN,
	CRITICAL,
	BULLET_COUNT,
	PLAYER_HP,
	FOCUS_NPC_HP,
	MISSION_ITEM_PERCENT,
	ON_MISSIONITEM,
	EXIT_MISSIONITEM,
	TRIGGER_MISSIONITEM,
	PLAYER_ONHIT,
	FILL_BULLET_PERCENT,
	FOCUS_ON_ARMORBOX,
	NOARMOR,
	PLAYER_DODDGE,
	PLAYER_GET_BULLET,
	NPC_ONHIT,
	BOSS_HP_PERCENT,
	BOSS_APPEAR,
	BOSS_DEAD,
	COUNTDOWN_PERCENT,
	MISSION_TIME_LIMITED,
	SHOW_BOSS_SKILL_EFFECT
}
