using System;

namespace DataCenter
{
	public enum AchievementType
	{
		PASS_CHECKPOINT = 1,
		KILL_ENEMY,
		HEADSHOT,
		USE_GRENADE,
		USE_MEDKIT,
		GAIN_DNA,
		TALENT_UPGRADE,
		GAIN_EQUIPMENT,
		EQUIPMENT_UPGRADE,
		OPEN_BOXES,
		GAIN_WEAPON,
		WEAPON_UPGRADE,
		PISTOL_KILL,
		MACHINEGUN_KILL,
		SHOTGUN_KILL,
		CONVOY_CHECKPOINT,
		DEFENSE_CHECKPOINT,
		TRANSPORT_CHECKPOINT,
		WIPEOUT_CHECKPOINT,
		KILL_INFERNALMOBS_BOMBER,
		KILL_INFERNALMOBS_SPITTER,
		KILL_INFERNALMOBS_BUTCHER,
		FAMILY_PORTRAIT,
		USE_GOLD,
		USE_DIAMOND,
		PLAY_AD_TIMES,
		LOGIN_DAYS
	}
}
