using System;

namespace DataCenter
{
	public enum CommonDataType
	{
		GOLD = 1,
		DIAMOND,
		DNA,
		REVIVE_COIN,
		VIP = 101,
		MONTHLY_CARD,
		EACH_LEVEL_AWARD_GIFT,
		DOUBLE = 201,
		ADDITIONAL_GOLD = 301,
		ADDITIONAL_DIAMOND,
		ADDITIONAL_DNA,
		BOX_COPPER = 401,
		BOX_SILVER,
		BOX_GOLDEN,
		RANDOM_WEAPON_DEBRIS_0 = 520,
		RANDOM_WEAPON_DEBRIS_1,
		RANDOM_WEAPON_DEBRIS_2,
		RANDOM_WEAPON_DEBRIS_3,
		RANDOM_WEAPON_DEBRIS_4,
		RANDOM_WEAPON_DEBRIS_5,
		RANDOM_PROP_DEBRIS_1 = 541,
		RANDOM_PROP_DEBRIS_2,
		RANDOM_PROP_DEBRIS_3,
		RANDOM_PROP_DEBRIS_4,
		RANDOM_PROP_DEBRIS_5
	}
}
