using System;

namespace DataCenter
{
	public enum Talent
	{
		PICKUP_RANGE,
		BULLET_ACROSS_PROBABILITY,
		RADAR_RANGE,
		BOMB_RANGE,
		CONTINUOUS_KILL_COIN,
		ADRENALINE_TIME,
		NO_CONSUME_BULLET_PROBABILITY,
		FLASH_RELOAD_PROBABILITY,
		BOMB_DAMAGE,
		BULLET_LIMIT,
		TURRET_DETECT_RANGE,
		AIM_MOVESPEED,
		DOUBLE_COIN_PROBABILITY,
		DAMAGE_2_ELITE,
		TURRET_DAMAGE,
		DOUBLE_DNA_PROBABILITY,
		MORE_DIAMOND,
		HEADSHOT_DAMAGE,
		DAMAGE_2_NORMAL,
		CRITICAL_PROBABILITY
	}
}
